version: "3"
services: 
  redis:
    image : redis
    container_name: redis

  web:
    build: ./signaling
    image: gcr.io/webrtc-202106/signaling:v1
    container_name: web
    ports: 
      - 8080:80

